mkdata:mkdata.c
	gcc -o ./BIN/mkdata.o mkdata.c -Wall
reshape_data:reshape_data.c
	gcc -o ./BIN/reshape_data.o reshape_data.c -Wall
ObservationPoints:ObservationPoints.c
	gcc -o ./BIN/ObservationPoints.o ObservationPoints.c -Wall